### ISSUE TITLE
Git package

### ISSUE THREAD

**Issue by Jrecos** [xemuliam/docker-dbt#3]
Hello!

this is not an issue at all, I'm trying to use this image to run some current dbt projects.

My dbt projects have some dependencies to Git packages and I'm not able to run them because git is not installed in the image.

I tried to add git to the list of packages installed in line 9 and that does not work, I'm not sure why.

Maybe we can add/fix this? 

Thanks!!

**Comment by Jrecos** [comment]
@elvuel @xemuliam Hello

**Comment by xemuliam** [comment]
Hi @Jrecos ,
what would you like to achieve?
Could you explain the process how you plan to use the image? Smth. like step by step plan.

**Comment by xemuliam** [comment]
Anyway, if you just wanted to add git packeges into your final image thyen you can amend last part of your `Dockerfile` in following way:

```dockerfile
FROM        base
LABEL       maintainer="Slava Kalashnikov <xemuliam@gmail.com>"
COPY        --from=build ${DBT_HOME} ${DBT_HOME}
RUN         cd ${DBT_HOME} && \
            export DEBIAN_FRONTEND=noninteractive && \
            apt-get update && \
            apt-get install -y --no-install-recommends git && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/* && \
            pip --no-cache-dir install \
              --find-links ${DBT_HOME}/wheels \
              --no-index -r plugins.txt
WORKDIR     ${DBT_HOME}
CMD         ["dbt", "--version"]
```

However let me remind that it is better when docker image contains app code inside it or has attached volume with the app code rather than using git command.

Here you can see the example how I use dbt in docker:
```yaml
version: "3.9"
services:
  sdp-poc-dbt:
    image: xemuliam/dbt:bigquery
    volumes:
      - $PWD:/usr/app
      - $PWD/profiles.yml:/root/.dbt/profiles.yml
      - $PWD/../../dbt-sa.json:/opt/secrets/secret.json
    environment:
      BUSINESS_REGION: EU
    command: sh -c "dbt run --select +Order"
```
There you can see three volumes:
- application code
- dbt profiles config file
- service account security file

If you work in this way then you are totally flexible to make any changes in configuration and code w/o touching (and rebuilding) docker image itself. Thus your work become more or less image agnostic.

Hope it helps 😉
